apiVersion: v2
name: giropops
description: Primeiro chart do Nginx criado no treinamento
type: application
version: 0.1.1
appVersion: "1.19.9"
keywords:
  - nginx
  - primeira_aula
  - webserver
home: https://github.com/badtuxx/DescomplicandoHelm
sources:
  - https://linuxtips.com.br
maintainers:
- name: Jeferson Fernando
  email: jeferson@linuxtips.com.br
deprecated: false
